/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangesIndexRouteImport } from './routes/changes.index'
import { Route as ChangesChangeIdRouteImport } from './routes/changes.$changeId'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesIndexRoute = ChangesIndexRouteImport.update({
  id: '/changes/',
  path: '/changes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesChangeIdRoute = ChangesChangeIdRouteImport.update({
  id: '/changes/$changeId',
  path: '/changes/$changeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/changes/': typeof ChangesIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/changes': typeof ChangesIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/changes/': typeof ChangesIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/changes/$changeId' | '/changes/' | '/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/changes/$changeId' | '/changes' | '/scenarios'
  id: '__root__' | '/' | '/changes/$changeId' | '/changes/' | '/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangesChangeIdRoute: typeof ChangesChangeIdRoute
  ChangesIndexRoute: typeof ChangesIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes/': {
      id: '/changes/'
      path: '/changes'
      fullPath: '/changes/'
      preLoaderRoute: typeof ChangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes/$changeId': {
      id: '/changes/$changeId'
      path: '/changes/$changeId'
      fullPath: '/changes/$changeId'
      preLoaderRoute: typeof ChangesChangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangesChangeIdRoute: ChangesChangeIdRoute,
  ChangesIndexRoute: ChangesIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
