/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExecutionsRouteImport } from './routes/executions'
import { Route as GateRouteImport } from './routes/gate'
import { Route as ChangesIndexRouteImport } from './routes/changes.index'
import { Route as ChangesChangeIdRouteImport } from './routes/changes.$changeId'
import { Route as FindingsIndexRouteImport } from './routes/findings.index'
import { Route as FindingsFindingIdRouteImport } from './routes/findings.$findingId'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios.index'
import { Route as ScenariosScenarioIdRouteImport } from './routes/scenarios.$scenarioId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsRoute = ExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesIndexRoute = ChangesIndexRouteImport.update({
  id: '/changes/',
  path: '/changes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesChangeIdRoute = ChangesChangeIdRouteImport.update({
  id: '/changes/$changeId',
  path: '/changes/$changeId',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsIndexRoute = FindingsIndexRouteImport.update({
  id: '/findings/',
  path: '/findings/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsFindingIdRoute = FindingsFindingIdRouteImport.update({
  id: '/findings/$findingId',
  path: '/findings/$findingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosScenarioIdRoute = ScenariosScenarioIdRouteImport.update({
  id: '/scenarios/$scenarioId',
  path: '/scenarios/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRoute
  '/gate': typeof GateRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/changes/': typeof ChangesIndexRoute
  '/findings/': typeof FindingsIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRoute
  '/gate': typeof GateRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/changes': typeof ChangesIndexRoute
  '/findings': typeof FindingsIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/executions': typeof ExecutionsRoute
  '/gate': typeof GateRoute
  '/changes/$changeId': typeof ChangesChangeIdRoute
  '/findings/$findingId': typeof FindingsFindingIdRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
  '/changes/': typeof ChangesIndexRoute
  '/findings/': typeof FindingsIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/executions'
    | '/gate'
    | '/changes/$changeId'
    | '/findings/$findingId'
    | '/scenarios/$scenarioId'
    | '/changes/'
    | '/findings/'
    | '/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/executions'
    | '/gate'
    | '/changes/$changeId'
    | '/findings/$findingId'
    | '/scenarios/$scenarioId'
    | '/changes'
    | '/findings'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/executions'
    | '/gate'
    | '/changes/$changeId'
    | '/findings/$findingId'
    | '/scenarios/$scenarioId'
    | '/changes/'
    | '/findings/'
    | '/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecutionsRoute: typeof ExecutionsRoute
  GateRoute: typeof GateRoute
  ChangesChangeIdRoute: typeof ChangesChangeIdRoute
  FindingsFindingIdRoute: typeof FindingsFindingIdRoute
  ScenariosScenarioIdRoute: typeof ScenariosScenarioIdRoute
  ChangesIndexRoute: typeof ChangesIndexRoute
  FindingsIndexRoute: typeof FindingsIndexRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions': {
      id: '/executions'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof ExecutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes/': {
      id: '/changes/'
      path: '/changes'
      fullPath: '/changes/'
      preLoaderRoute: typeof ChangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes/$changeId': {
      id: '/changes/$changeId'
      path: '/changes/$changeId'
      fullPath: '/changes/$changeId'
      preLoaderRoute: typeof ChangesChangeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/': {
      id: '/findings/'
      path: '/findings'
      fullPath: '/findings/'
      preLoaderRoute: typeof FindingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings/$findingId': {
      id: '/findings/$findingId'
      path: '/findings/$findingId'
      fullPath: '/findings/$findingId'
      preLoaderRoute: typeof FindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId': {
      id: '/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof ScenariosScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecutionsRoute: ExecutionsRoute,
  GateRoute: GateRoute,
  ChangesChangeIdRoute: ChangesChangeIdRoute,
  FindingsFindingIdRoute: FindingsFindingIdRoute,
  ScenariosScenarioIdRoute: ScenariosScenarioIdRoute,
  ChangesIndexRoute: ChangesIndexRoute,
  FindingsIndexRoute: FindingsIndexRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
